# Node.js with Angular


trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'

- task: PushToHeroku@0
  inputs:
    ApiKey: '4226cadc-853b-4d62-842b-da5ac9f1e073'
    AppName: 'vertex-mytextbook'
    PushRoot: 'my-text-book/dist'

